### ISSUE TITLE
It crashed

### ISSUE THREAD

**Issue by GalaxyMan042309** [UnsignedArduino/Bloons-Tower-Defense-v3#1]
It just crashed help me please

**Comment by UnsignedArduino** [comment]
Can you please elaborate? And make sure you are using the [Arcade link](https://forum.makecode.com/t/bloons-tower-defense-v3/9688?u=unsignedarduino) on the [forum page](https://forum.makecode.com/t/bloons-tower-defense-v3/9688) as the GitHub page for this project doesn't have anything generated for it.
